bbs:
    name: Maiks Place BBS
    sysop: Mike Dreier
    new_user_sl: 10
    menus_dir: configs/menus
database:
    path: data/nullmodem.sqlite
telnet:
    enabled: true
    addr: :2323
ssh:
    enabled: true
    addr: :2222
    host_key_path: data/ssh_host_key
